### PR TITLE
Buffer size increased to 2^20 (1 MB)

### PR DESCRIPTION
**Pull request by seal-hg**
Buffer size was too small.

### CODE REVIEW

**Comment by williamkapke** [comment]
This seems really large for creating the metadata of the message. A 2nd buffer is created to accommodate the message data here:
https://github.com/williamkapke/ipp/blob/master/lib/serializer.js#L244

Maybe you have a scenario where it needs to be this large? I haven't seen it and would love to know... Can you share what takes up that much space?

**Comment by seal-hg** [comment]
We are implementing an IPP server that also has to support CUPS operations. One of these CUPS operations is 'CupsGetPrinters' which is supposed to deliver all printers in the system and it has to deliver it in the metadata (printer attributes group). If we stick to a buffer size of 10KB, only up to 200 printers would fit into the response. But we have systems with thousands of printers. So increasing the buffer to 1MB would at least allow us to support up to 20000 printers.

**Comment by williamkapke** [comment]
Wow that's amazing and really interesting!

Ok. IoT folks like to keep memory allocation to the minimum. Let's make this work for everyone- it needs to be configurable. 

Think you can add a way to configure it with it defaulting to what is is now?

**Comment by williamkapke** [comment]
Wow that's amazing and really interesting!

Ok. IoT folks like to keep memory allocation to the minimum. Let's make this work for everyone- it needs to be configurable. 

Think you can add a way to configure it with it defaulting to what is is now?

**Comment by williamkapke** [comment]
Accidental close- sry

**Pull request merged**
